### ISSUE TITLE
Typo to be fixed #2

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/js-object-oriented-object-methods-readme#5]
So how did this all come together? We put together our knowledge that when create an object with a constructor function, this refers to that newly created object. Then we used that knowledge to assign each newly created object an attribute of sayHello that points to a function. Finally, we had that method reference data specific to it's object with use of this.

FIrst line, fix, add we  -- near the end, that when WE create an object...

**Comment by cjbrock** [comment]
Fixed! Thank you for the edit.

// Corinna
